### ISSUE TITLE
Edit profile

### ISSUE THREAD

**Issue by alexrobincrabbe** [alexrobincrabbe/Wordwell#14]
AS a user I can edit my profile so that I can share information about myself with other users

### Acceptance Criteria

- I can click a button on my profile page to open a form to edit my profile
- I can upload a picture which is displayed on my profile
- I can complete an about me section to share information about myself
- I see a confirmation when I update my profile

### Tasks

- [ ] create a button on the profile page, which is only visible to the owner of the profile, and opens the edit profiel form page
- [ ] create a form which allows the user to edit email, profile picture, display name and about me sectiojns
- [ ] create a hmtl template to display the form
- [ ] create a view to prepopulate the form, handle post data, and update the database
