### ISSUE TITLE
View profile page

### ISSUE THREAD

**Issue by alexrobincrabbe** [alexrobincrabbe/Wordwell#15]
As a user I can view my own and other users profiles, to see information about other users

### Acceptance Criteria

- I can click on a link on the navbar to view my profile
- I can click on the names of other users to view their profiles
- I can view the about me section of other users
- I can see when other users joined the site, and when they were last active

### Tasks

- [ ] Create a navbar link that links to the profile view of the logged in user
- [ ] Create a model to contain the profile information of users
- [ ] Create a signal to create the profile instance when a user is created
- [ ] Create a html template to display the profile
- [ ] Create a view to sent to context data to the template
- [ ] Modify the message board, and link the names of authors to their profile
