### ISSUE TITLE
View high score page

### ISSUE THREAD

**Issue by alexrobincrabbe** [alexrobincrabbe/Wordwell#16]
As a user I can view the highscores of all users so that I can compare my score with the scores of other users

### Acceptance Criteria

- I can click on a link on the navbar to view the high scores page
- I can view a list of users, ordered by their high scores, from highest to lowest
- I can click on the name of a user to view their profile

### Tasks

- [ ] create a model to save the scores of all users
- [ ] create a link on the navbar that links to the high score page url
- [ ] create a html template which displays the high scores of users, along with their username and profiel picture
- [ ] create a view to get the highscores from the database, and order them, before sending the context data to the template
