### ISSUE TITLE
Game Board

### ISSUE THREAD

**Issue by alexrobincrabbe** [alexrobincrabbe/Wordwell#17]
As a player  can view the game board so that I can guess words to play the game

### Acceptance Criteria

- I can click a link on the navbar that takes me to the game board
- The game board is visible, and the letters are reshuffled every time I view the board

### Tasks

- [x] create a link on the navbar that links to the game board url
- [x] create a html template to contains the board
- [x] create a view that directs to the html template
- [x] create a javascript function that randomly shuffles an array of letters
- [x] create a javascript function that displays the letters on the tiles on the board
