### ISSUE TITLE
Guess words on the board

### ISSUE THREAD

**Issue by alexrobincrabbe** [alexrobincrabbe/Wordwell#19]
As a player I can guess words so that I can score points in the game

### Acceptance Criteria

- I can type a word, and if the word is on the board, it will be displayed on a list when I press enter
- As I type, the letters are highlighted on the board so that I have confirmation that the word is a valid word on the board

### Tasks

- [x] create a javascript search function, to search the board for a word, and return a value of true of the word is found on the board
- [x] create an event listener to add letters to a word string as the user types a word
- [x] create an event listener to submit the word, and clear the string when the user presses enter
- [x] create a function to check the string in the search board function, as the user types
- [x] create a function to highlight the tiles on the board which the player has typed
