### ISSUE TITLE
Check words in the dictionary

### ISSUE THREAD

**Issue by alexrobincrabbe** [alexrobincrabbe/Wordwell#20]
As a player, I can guess valid dictionary words on the game board to score points.

### Acceptance Criteria

- If a guessed word is in the dictionary, it is added to the list of guessed words
- If the word is not in the dictionary, a message is displayed to confirm it is not valid

### Tasks

- [x]  Create a view to access a Json dictionary
- [x]  Load the dictionary in the game Javascript using the fetch API
- [x]  Write a function that checks if a string is a word in the dictionary
- [x] If the word is not in the dictionary, update the html content to display a message confirming the the word is not valid
