### ISSUE TITLE
Game timer

### ISSUE THREAD

**Issue by alexrobincrabbe** [alexrobincrabbe/Wordwell#21]
As a player, I can start a game timer so that I can guess as many words as possible before the timer runs out.

### Acceptance Criteria

-  I can click a button to start the game
- A timer is displays which counts down to zero
- When the timer reaches zero, I can no longer enter words
- When the timer reaches zero, I can start a new game

### Tasks

- [x] Add a start game button to the html template
- [x] Add a start game button to the html template
- [x] Add an interval function to the game javascript to countdown the timer
- [x] Add an event listener to the start button to start the timer and hide the start and reshuffle buttons
- [x] modify the javascript so that scoring is only allowed if the timer it above zero
- [x] Add an event listener to refresh the page when the restart  button is clicked
