### ISSUE TITLE
Save score

### ISSUE THREAD

**Issue by alexrobincrabbe** [alexrobincrabbe/Wordwell#22]
As a player I can save my score so that I can compare my high score with other users, and beat my own high score.

### Acceptance Criteria

- I can click a button at the end of a game to save my score
- I can view the high score on my profile
- I can view my own and other players high score on the high score board

### Tasks

- [x] Add a save score button to the html template
- [x] Show the button when the timer reaches zero
- [x] create a form object with javascript to submit the score as post data
- [x] Add a high score field to the UserProfile Model
- [x] Create a view to save the score, and update the highscore field if neccessary
