### ISSUE TITLE
View Landing Page

### ISSUE THREAD

**Issue by alexrobincrabbe** [alexrobincrabbe/Wordwell#24]
As a site user I can read the game instructions and overview of the website so that I know what the site is for and how to use it.

### Acceptance Criteria

- A link to the home page appears in the navbar
- The game instructions are displayed on the homepage
- The user is prompted to log in to use restricted site functions

### Tasks

- [x] Add a link that links to the homepage url on the navbar
- [x] Add a html template with content describing the site and the rules of the game
- [x] Add a link to the message boards, and a sign in link
- [x] Create a view to direct the url to the landing page
