### ISSUE TITLE
Automatic test: update profile

### ISSUE THREAD

**Issue by alexrobincrabbe** [alexrobincrabbe/Wordwell#26]
AS a developer I can automatically test the update profiel view so that I can be confident the view is functioning correctly.

### Acceptance Criteria

- The page returns a status of 200
- The returned html contains the relevant confirmation message if the form is valid and submitted
- The update profile form validates when a display name is provided, and a valid email is provided(if the email if filled out)

### Tasks

- [x] Create a test for the view that fails each of the above criteria
- [x] Creat a test for the view that passes all of the above criteria
- [x]  Create a test for the form that fails each of the above criteria
- [ ]  Create a test for the form that passes all of the above criteria
