### ISSUE TITLE
View Message Board

### ISSUE THREAD

**Issue by alexrobincrabbe** [alexrobincrabbe/Wordwell#6]
As a user I can view all posts that have been created on the site that I can see posts made by other users, and posts I have created myself.

### Acceptance Criteria

- I can click on a link on the navbar to view the message board
- I can view a list of all posts
- The posts should be paginated, with 10 posts displayed per page
- The posts shoudl be ordered, by most recent activity,with the newest posts displayed at the top of the first page
- The title of the post should be visible
- The author of each post should be visible
- The number of replies each post has received should be visible

### Tasks

- [x] create link to the messge board on the navbar
- [x] create a model to contain the required fields for the posts
- [x] create a html template which displays all Post Objects on the page
- [x] create a view that sends the required post data as context to the html template, and sorts the posts by newest reply or create date of the post if there are no replies
