### ISSUE TITLE
Create New Post

### ISSUE THREAD

**Issue by alexrobincrabbe** [alexrobincrabbe/Wordwell#7]
As a user I can create new posts so that I can ask questions or share information with other users on the site

### Acceptance Criteria

- I can click on a button on the message board to create a new post
- I can complete the title and body of my message
- I see a confirmation message when my post has been created, and I am redirected to the message board to view my post

#### Tasks
- [x] Create a button on the message board that call the view to create a post when clicked
- [x] Create a form to create a new post
- [x] Create a hmtl template that displays the form, and submits the form data
- [x] Create a view that handles the post data sent from the html template and saves it to the database
