### ISSUE TITLE
View Post

### ISSUE THREAD

**Issue by alexrobincrabbe** [alexrobincrabbe/Wordwell#8]
As a user I can view the content of posts made by other users so than I can interact with other users on the site

### Acceptance Criteria

- I can click on a message on the message board to see the contents of the post

### Tasks
- [x] Create a html template that displays the title, content and create date of a post
- [x] Link the post titles on the message board to the correct url to display each post
- [x] Create a view that handles the url to send the relevent context data to the html template
